services:
  main-app-1:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: main-app:local
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/opt/app/log/main
    env_file:
      - .env-app

  main-app-2:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: main-app:local
    ports:
      - "8002:8000"
    volumes:
      - ./logs:/opt/app/log/main
    env_file:
      - .env-app

  order-processor:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.processor
    image: order-processor:local
    container_name: order-processor
    expose:
      - "8000"
    volumes:
      - ./logs:/app/log/modules
    env_file:
      - .env-app

  fluentd:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fluentd
    container_name: fluentd
    volumes:
      - ../fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/app:ro
    env_file:
      - .env-fluentd
    depends_on:
      - main-app-1
      - main-app-2
      - order-processor