version: '3.8'

services:
  app-1:
    container_name: awesome-backend-app-1
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - awesome-backend-network-1
      - rabbit-net
      - redis-net
    healthcheck:
      test: [ "CMD", "curl","-f", "http://app-1:8080/awesome-backend/healthcheck" ]
      timeout: 10s
      retries: 5
    restart: always
  app-2:
    container_name: awesome-backend-app-2
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - awesome-backend-network-2
      - rabbit-net
      - redis-net
    healthcheck:
      test: [ "CMD", "curl","-f", "http://app-2:8080/awesome-backend/healthcheck" ]
      timeout: 10s
      retries: 5
    restart: always

  app-checker:
    container_name: app-checker
    image: curlimages/curl:8.18.0
    networks:
      - awesome-backend-network-1
      - awesome-backend-network-2
    command: >
      /bin/sh -c '
              while true; do
                echo "[$$(date)] Проверка /healthcheck приложения..."

                HTTP_CODE1=$$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://awesome-backend-app-1:8080/awesome-backend/healthcheck 2>/dev/null || echo "000")
                             if [ "$$HTTP_CODE1" = "503" ] || [ "$$HTTP_CODE1" = "000" ]; then
                                echo "[$$(date)] ❌ Получен 503 (или нет соединения)"
                                exit 1
                             fi
                HTTP_COD2E=$$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://awesome-backend-app-2:8080/awesome-backend/healthcheck 2>/dev/null || echo "000")
                             if [ "$$HTTP_CODE2" = "503" ] || [ "$$HTTP_CODE2" = "000" ]; then
                                echo "[$$(date)] ❌ Получен 503 (или нет соединения)"
                                exit 1
                             fi

                echo "[$$(date)] ✓ Приложение здорово"
                sleep 10
              done
            '
    depends_on:
      - app-1
      - app-2
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 10s
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis-net

  pg-master:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: local-postgres:patroni
    container_name: pg-master
    hostname: pg-master
    env_file:
      - .env
    expose:
      - 8008
    ports:
      - "5433:5432"
    networks:
      - db-net
      - zoo-net
    volumes:
      - pg-master:/var/lib/postgresql/data
    command: patroni /postgres0.yml

  pg-slave:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: local-postgres:patroni
    container_name: pg-slave
    hostname: pg-slave
    expose:
      - 8008
    ports:
      - "5434:5432"
    volumes:
      - pg-slave:/var/lib/postgresql/data
    networks:
      - db-net
      - zoo-net
    env_file:
      - .env
    command: patroni /postgres1.yml

  zoo:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zoo
    hostname: zoo
    ports:
      - "2181:2181"
    networks:
      - zoo-net
    env_file:
      - .env

  haproxy:
    image: haproxy:3.0
    container_name: api-gateway
    ports:
      - "5432:5432"
      - "7000:7000"
      - "8081:8080"
    depends_on:
      - pg-master
      - pg-slave
      - zoo
    networks:
      - api-gateway
      - db-net
      - awesome-backend-network-1
      - awesome-backend-network-2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped


volumes:
  redis_data:
  rabbitmq-data:
  pg-master:
  pg-slave:
networks:
  api-gateway:
    driver: bridge
  db-net:
    driver: bridge
  zoo-net:
    driver: bridge
  awesome-backend-network-1:
    driver: bridge
  awesome-backend-network-2:
    driver: bridge
  rabbit-net:
    driver: bridge
  redis-net:
    driver: bridge
