FROM alpine:3.20 AS builder

RUN apk add --no-cache g++ musl-dev make
WORKDIR /opt
COPY app/server.cpp .

RUN g++ -O2 -static -s -std=c++17 -pthread server.cpp -o server


FROM scratch AS runtime

USER 10001
WORKDIR /app
COPY --from=builder /opt/server /app/server

EXPOSE 8888
ENTRYPOINT ["/app/server"]
