FROM python:latest

COPY . .

RUN apt-get update
RUN apt-get install -y curl
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]